### PR TITLE
new prop: closeSuggestionsOnSelect

### PR DESCRIPTION
**Pull request by plysik**
I've added new prop: 'closeSuggestionsOnSelect'.

It allows controling autoclosing suggestions that happens after suggestion selecting.

### CODE REVIEW

**Comment by noah-potter** [comment]
I think a better prop would be something like `keepSuggestionsOnSelect`, that way it defaults to false

**Comment by plysik** [comment]
done

**Comment by pimterry** [comment]
Hi - sorry for the delay here. This looks like a great suggestion, and a really useful feature, but it's quite hard to review because the change reformats a lot of the existing code. On master you can use prettier to reformat the source, by running `npm run prettier -- src`, which should easily get you back to the standard formatting, and make the changes themselves a bit clearer. Unfortunately there's also now conflicts with the current state of master too, so it's not currently mergeable.

If you're still interested in this change, would you be open to looking into that? I know a lot of time has passed here, so no problem if not, just let us know.

**Comment by pimterry** [comment]
Hi @plysik, did you have any thoughts on the above? I'd love to get this merged if it's still useful to you. If not, no worries, but I will close this PR in a few days.

**Pull request closed without merging**
