### PR TITLE
fix: readme usage example fix, rebind context for functions to pass

### PR DESCRIPTION
**Pull request by westfalensgod**
Hello!

Fixed the usage example in README.md, rebound context of the methods.

### CODE REVIEW

**Comment by moroshko** [comment]
What's wrong with the current approach?

**Comment by westfalensgod** [comment]
I came across some problems with it, since it's failing to compile. The version which I committed works perfectly though.

**Comment by moroshko** [comment]
We use the new "class instance fields" proposal in docs.
See [here](https://medium.freecodecamp.org/react-binding-patterns-5-approaches-for-handling-this-92c651b5af56#f45f).

**Comment by westfalensgod** [comment]
Thank you and I apologize for wasting your time.

**Pull request closed without merging**
