### PR TITLE
Support for Bower Components

### PR DESCRIPTION
**Pull request by yagudaev**
Added support for bower.

The only thing I am not sure about is the versioning. Should we label it 2.0.0? And release it as part of the 2.0 release? Or 1.18.1 (I used 1.18.2 just because I messed up the first time and 1.18.1 doesn't work properly).

### CODE REVIEW

**Comment by moroshko** [comment]
@yagudaev Thanks for the PR!

Is there a way to remove 1.18.1 from bower? Can I push to bower at all if you are the owner?

**Comment by moroshko** [comment]
@yagudaev I'd appreciate if you could [unregister](http://bower.io/docs/creating-packages/#unregister) react-autosuggest from bower, so that I could register it and keep pushing updates.

**Comment by yagudaev** [comment]
Sure thing :). Consider it done.

**Comment by moroshko** [comment]
@yagudaev Thanks!

I registered my repo with bower. However, bower search still shows your version from 6 days ago. Maybe it needs some time to sync. Let's wait a bit to see if it updates itself.

Anyway, please let me know if you were able to successfully consume the package.

**Comment by yagudaev** [comment]
Works great! Thanks Misha :).

**Pull request merged**
