### PR TITLE
Fixes sticky suggestions for touch devices

### LINKED ISSUE #412: Suggestions list stuck open after dragging a suggestion outside of the autosuggest
Issue from here: https://github.com/callemall/material-ui/issues/7526#

### PR DESCRIPTION
**Pull request by d-a-n**
When scrolling on the suggestion list with touch devices and the input looses focus, the suggestions don't disappear as expected.

Fixes  #412 #380

### CODE REVIEW

**Comment by moroshko** [comment]
Thanks for this!

Does this really fix #412? 
Isn't `onTouchEnd` a mobile only thing?
Did you test [this repro](https://github.com/moroshko/react-autosuggest/issues/412#issuecomment-318627754) on desktop?

**Comment by d-a-n** [comment]
@moroshko Thanks for you fast reply. I've pushed the missing part ;)

ezgif-4-76db2099a5

**Comment by moroshko** [comment]
@d-a-n I deployed your version [here](https://ra.now.sh/), but it doesn't seem to behave as expected. Specifically:

1. In [#412 repro](https://github.com/moroshko/react-autosuggest/issues/412#issuecomment-318627754), the last bit doesn't work:
> Clicking outside of the autosuggest closes the suggestions. 

2. #380 -Trying to click outside of the autosuggest **on iOS**, doesn't close the suggestions list. It works on desktop, but not on iOS (tested on iPhone 6+ Chrome).

**Comment by d-a-n** [comment]
@moroshko Thanks for pointing this out.

I've fixed `Clicking outside of the autosuggest closes the suggestions.` from #412.

Regarding blurring the the input on touch devices when a users clicks outside: This could be done too but atm it reflects the default browser behavior. I would not change this. Probably most of the users will use the keyboards done or enter key to dismiss the suggestion list anyways. What do you think?

**Comment by moroshko** [comment]
@d-a-n 

#412 
Check out The **Multiple sections** example [here](https://dist-usikpayhrn.now.sh/).
We have `highlightFirstSuggestion={true}` in this example.
The problem is that, with your changes, the first suggestion is highlighted after you drag a suggestion. We should not highlight the first suggestion in this case.

#380
I'm not saying we should blur the input when user clicks outside. I'm saying that the suggestions list needs to be closed. I'm OK with leaving the input focused.
If you still want to fix this, I suggest to create a separate PR for #380.

**Pull request closed without merging**
