### PR TITLE
added Browsable props for open suggestions with click

### PR DESCRIPTION
**Pull request by uxitten**
this props for open suggestions with user click

### CODE REVIEW

**Comment by aberezkin** [comment]
What problem are you trying to solve?

**Comment by uxitten** [comment]
This is about 2 years ago and I don't remember 😀

**Comment by aberezkin** [comment]
Fair notice. I'll close this PR as stale then :)

**Comment by uxitten** [comment]
I think this PR about possibility user to browsing a list without type anything

**Pull request closed without merging**
