### PR TITLE
Add isHighlighted to renderSuggestion data

### PR DESCRIPTION
**Pull request by mkaemmerer**
Fixes https://github.com/moroshko/react-autosuggest/issues/383

### CODE REVIEW

**Comment by mkaemmerer** [comment]
Before this can be merged, it should include the changes from react-autowhatever:
https://github.com/moroshko/react-autowhatever/pull/28

**Comment by moroshko** [comment]
I just released `react-autowhatever` 10.1.0. Could you upgrade it in `package.json`, and make sure that everything works as expected? A test would be appreciated.

**Comment by mkaemmerer** [comment]
Thanks! I'll get right on that.

**Comment by mkaemmerer** [comment]
@moroshko, I added a couple of commits. Can you take another look?

**Comment by moroshko** [comment]
Published as [v9.1.0](https://github.com/moroshko/react-autosuggest/releases/tag/v9.1.0).
Thanks again for your contribution!

**Comment by mkaemmerer** [comment]
You're welcome. And thanks for writing a great library

**Pull request merged**
