### PR TITLE
Enforce node != document checks

### PR DESCRIPTION
**Pull request by lPadier**
Check that node is not document nor null on first iteration.

### CODE REVIEW

**Comment by moroshko** [comment]
Could you explain the problem you are trying to solve?

**Comment by lPadier** [comment]
In the app I'm building, `node.getAttribute('data-suggestion-index')` sometimes fails on IE 11 with the following error message: "object does not support property or method getAttribute". Checking that node !== document or null before the first loop iteration should avoid event.target being document

**Comment by moroshko** [comment]
Thanks!
Did you test that this change solves the issue in IE11?

**Comment by lPadier** [comment]
Dispatching a mousedown event on document with this change no longer throws an error on IE11

**Comment by moroshko** [comment]
[v8.0.1](https://github.com/moroshko/react-autosuggest/releases/tag/v8.0.1) contains this fix. Thanks!

**Comment by Degee** [comment]
Actually i am getting exactly the same error with version 9.3.2 of autosuggest 

`object does not support property or method getAttribute`

I think this was not really a solution. Weird thing is that error sometimes randomly dissappears.

**Pull request merged**
