### PR TITLE
fix: Fire onSuggestionSelected when Tab key is pressed

### PR DESCRIPTION
**Pull request by jarlah**
Trying to implement what has been discussed in issue #332 .

Does not build, because i am not good at finding out how to cover that tab key change. Fails due to 90.68 is lower than 91 % test coverage :P

### CODE REVIEW

**Comment by jarlah** [comment]
Could potentially refactor stuff so that it becomes:

```
case 9:
case 13:
  this.selectHighlightedItem(event);
  break;
```
or something somethning

**Comment by jarlah** [comment]
no comments on this one? is this relevant? or irrelevant?

**Comment by davityavryan** [comment]
Hey @moroshko,

When you are planing to push this?

There should be just Click aaaand it's merged.

**Comment by mykter** [comment]
PR #333 was a more comprehensive change, but it was rejected. For now I'm just patching it locally to get this behaviour.

Would a PR that had it as a configurable property of the component be of interest?

**Pull request closed without merging**
