### PR TITLE
Simple improvement at workflow of development

### PR DESCRIPTION
**Pull request by cauealves**
This is a simple change to open the URL after creating the server with `npm start` command.

### CODE REVIEW

**Comment by rickhanlonii** [comment]
@moroshko @cauealves what do you think about putting this behind an `--open` flag of some sort rather than default behavior?

**Comment by cauealves** [comment]
@rickhanlonii It's possible. I'm not sure if this is really necessary. This is a common flow to those who are raising the server.. But it's a case to think about =) 

What did you think about this, @moroshko ?

**Comment by moroshko** [comment]
@cauealves I agree that most of the time you'd want to open the page manually, so why not to automate this :) Mind resolving the conflicts?

**Comment by cauealves** [comment]
@moroshko Of course. Now, everything is up to date =)

**Comment by moroshko** [comment]
Thanks!

**Pull request merged**
