### PR TITLE
resolving dependency vulnerabilities

### PR DESCRIPTION
**Pull request by szuke**
Updated semver dependency vulnerabilities
"terser-webpack-plugin": "^4.2.2",
isomorphic-fetch@3.0.0

Thanks a lot for contributing to react-autosuggest :beers:

Before submitting the Pull Request, please:

* write a clear description of what this Pull Request is trying to achieve
* `npm run build` to see that you didn't break anything

### CODE REVIEW

**Review by pimterry — CHANGES_REQUESTED** [review]
Thanks @szuke! Great contribution, updating packages like these is useful, but:

* You haven't committed the updates to package-lock.json, which is why the build is failing
* These are major version bumps - can you check the breaking changes for each package, and explain why they don't matter in our case (or deal with them if they do)?

**Comment by pimterry** [comment]
Hi @szuke are you still interested in this? I'd be happy to merge it if you've got a minute to look into my comments above. If not no worries, but I'll close this PR in a few days.

**Comment by szuke** [comment]
I'll tackle these changes. Thanks for your patience. I'm trying to do help out however possible. 

Scott

**Comment by pimterry** [comment]
Hi @szuke, I'm going to close this for now.

If you do find time in future to look at the above that would be great, let me know & we can reopen this or you can open a new PR. For the moment though I'm trying to clean up the list of open PRs to just the active ones in development, so I'm going to close this up.

**Pull request closed without merging**
