### PR TITLE
Add optional onSuggestionFocused prop

### LINKED ISSUE #168: Is onSuggestionFocused actually working?
I need to know when and which suggestion is focused (not selected yet). I read in old issues that there was a `onSuggestionFocused` property, but It's not documented and I wasn't able to use it.

### PR DESCRIPTION
**Pull request by kenny-hibino**
Resolves #168 

Added `onSuggestionFocused` prop (optional).

The function signature looks like the following:

```js
function onSuggestionFocused({ suggestion })
```

The function gets called every time focused suggestion changes.
When unfocused, the function will be called with `{ suggestion: null }`.

### CODE REVIEW

**Comment by woniesong92** [comment]
👍

**Comment by moroshko** [comment]
@kenny-hibino Sorry for the delayed response.

Could you please rename "focused" to "highlighted". We moved to use the term "highlighted" across the repo to avoid the confusion with html focus.

    onSuggestionFocused => onSuggestionHighlighted
    hasFocusedSuggestionChanged => hasHighlightedSuggestionChanged

    etc...

Also, could you please rebase on master?

**Comment by kenny-hibino** [comment]
@moroshko Thank you for the response!
I rebased the feature branch on master, and renamed the prop to `onSuggestionHighlighted` 👍 
Please let me know if there's any other changes you want me to make.

**Comment by moroshko** [comment]
`onSuggestionHighlighted` is available in [v9.3.0](https://github.com/moroshko/react-autosuggest/releases/tag/v9.3.0) now.

**Comment by moroshko** [comment]
@kenny-hibino Thanks a lot for your contribution!

**Pull request merged**
